version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - microservices-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - microservices-network

  sale-service:
    build:
      context: ./sale-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
