server:
  port: 8082

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://jjmirandam_db_user:BJyZjBN4naetrmYU@clustersoe.bcqm3lu.mongodb.net/app?retryWrites=true&w=majority&appName=ClusterSoe
